language: python
# Note that should use pip for all python libraries not apt-get
# We can install the system scipy and matplotlib because we only target 2.7
# (the system default)
python:
  - "2.7"
sudo: required
#dist: trusty
before_install:
  - for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt `lsb_release -cs` stable"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list
  - wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y openmodelica
  - sudo apt-get install -qq -y python-scipy python-matplotlib
  - pip2 install dymat pyswarm cma
install:
  - mkdir build
  - cd build
  - cmake ..
  - make
script:
  - ctest -V
